version: '3'
services:
  rabbitMq:
    image: rabbitmq
    container_name: rabbitMq_container
    
  paymentservice:
    image: paymentservice 
    container_name: payment_container
    ports:
     - "8080:8080"
    
  tokenservice:
    image: tokenservice 
    container_name: token_container

 
