version: '3'
services:
  rabbitmq:
    image: rabbitmq
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
     - "5672:5672"


  paymentservice:
    image: paymentservice 
    container_name: payment_container
    build: ../payment-service
    network_mode: host
    
  tokenservice:
    image: tokenservice 
    container_name: token_container
    build: ../token-service
    network_mode: host

  accountmanagementservice:
    container_name: accountmanagementservice 
    network_mode: host
    image: accountmanagementservice
    build: ../accountManager
